recipe: default.v1
language: en
assistant_id: crysos

pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
  
  - name: SpacyTokenizer
  
  - name: SpacyFeaturizer
    pooling: mean 
  
  - name: LexicalSyntacticFeaturizer
  
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 2
  
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  
  - name: DIETClassifier
    transformer_size: 64
    number_of_transformer_layers: 1
    number_of_attention_heads: 2
    embedding_dimension: 64
    epochs: 150
    batch_size: [64, 256]
    learning_rate: 0.001
    constrain_similarities: true
  
  - name: EntitySynonymMapper
  
  - name: FallbackClassifier
    threshold: 0.35
    ambiguity_threshold: 0.1

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_fallback" 
    enable_fallback_prediction: true
  
  - name: MemoizationPolicy
    max_history: 5
  
  - name: TEDPolicy
    max_history: 5  
    epochs: 50
    constrain_similarities: true
